swagger: "2.0"
info:
  title: Security Example API
  description: This API demonstrates the use of the goa security DSL
  termsofservice: ""
  contact: null
  license: null
  version: ""
  extensions: {}
host: localhost:8080
basepath: ""
schemes: []
consumes: []
produces: []
paths:
  /secure:
    ref: ""
    get:
      tags:
      - secured_service
      summary: secure secured_service
      description: This action is secured with the jwt scheme
      externaldocs: null
      operationid: secured_service#secure
      consumes: []
      produces: []
      parameters:
      - name: fail
        in: query
        description: Whether to force auth failure even with a valid JWT
        required: false
        schema: null
        type: boolean
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: string
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/SecureUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security: []
      extensions: {}
    put:
      tags:
      - secured_service
      summary: doubly_secure secured_service
      description: This action is secured with the jwt scheme and also requires an
        API key query string.
      externaldocs: null
      operationid: secured_service#doubly_secure
      consumes: []
      produces: []
      parameters:
      - name: k
        in: query
        description: API key
        required: false
        schema: null
        type: string
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: string
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/DoublySecureUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security: []
      extensions: {}
    post:
      tags:
      - secured_service
      summary: also_doubly_secure secured_service
      description: This action is secured with the jwt scheme and also requires an
        API key header.
      externaldocs: null
      operationid: secured_service#also_doubly_secure
      consumes: []
      produces: []
      parameters:
      - name: k
        in: query
        description: API key
        required: false
        schema: null
        type: string
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      - name: oauth
        in: query
        description: ""
        required: false
        schema: null
        type: string
        format: ""
        allowemptyvalue: false
        items: null
        collectionformat: ""
        default: null
        maximum: null
        exclusivemaximum: false
        minimum: null
        exclusiveminimum: false
        maxlength: null
        minlength: null
        pattern: ""
        maxitems: null
        minitems: null
        uniqueitems: false
        enum: []
        multipleof: 0
        extensions: {}
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: string
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: ""
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/AlsoDoublySecureUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security: []
      extensions: {}
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
  /signin:
    ref: ""
    get: null
    put: null
    post:
      tags:
      - secured_service
      summary: signin secured_service
      description: Creates a valid JWT
      externaldocs: null
      operationid: secured_service#signin
      consumes: []
      produces: []
      parameters: []
      responses:
        "204":
          description: No Content response.
          schema: null
          headers: {}
          ref: ""
          extensions: {}
        "401":
          description: Unauthorized response.
          schema:
            schema: ""
            id: ""
            title: ""
            type: ""
            items: null
            properties: {}
            definitions: {}
            description: ""
            defaultvalue: null
            example: null
            media: null
            readonly: false
            pathstart: ""
            links: []
            ref: '#/definitions/SigninUnauthorizedResponseBody'
            enum: []
            format: ""
            pattern: ""
            minimum: null
            maximum: null
            minlength: null
            maxlength: null
            required: []
            additionalproperties: false
            anyof: []
          headers: {}
          ref: ""
          extensions: {}
      schemes:
      - http
      deprecated: false
      security: []
      extensions: {}
    delete: null
    options: null
    head: null
    patch: null
    parameters: []
    extensions: {}
definitions:
  AlsoDoublySecureUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: AlsoDoublySecureUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Maxime ipsam esse et.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
  DoublySecureUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: DoublySecureUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Itaque accusamus enim.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
  SecureUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: SecureUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Accusantium voluptatem alias corrupti voluptates a.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
  SigninUnauthorizedResponseBody:
    schema: ""
    id: ""
    title: SigninUnauthorizedResponseBody
    type: string
    items: null
    properties: {}
    definitions: {}
    description: Credentials are invalid
    defaultvalue: null
    example: Tenetur est et.
    media: null
    readonly: false
    pathstart: ""
    links: []
    ref: ""
    enum: []
    format: ""
    pattern: ""
    minimum: null
    maximum: null
    minlength: null
    maxlength: null
    required: []
    additionalproperties: false
    anyof: []
parameters: {}
responses: {}
securitydefinitions: {}
tags: []
externaldocs:
  description: Security example README
  url: https://github.com/goadesign/plugins/security/tree/master/example/multi_auth/README.md
